PRACTICUM_TOKEN=1
TELEGRAM_TOKEN=2
TELEGRAM_CHAT_ID=3
ALL_TOKENS = {
    'PRACTICUM_TOKEN': PRACTICUM_TOKEN,
    'TELEGRAM_TOKEN':TELEGRAM_TOKEN,
    'TELEGRAM_CHAT_ID': TELEGRAM_CHAT_ID
}

for token_hame in ALL_TOKENS:
    print(token_hame)